const canvas = document.querySelector("canvas");

c = canvas.getContext("2d");

const text1 = "Use Arrow keys or W and D to move the player left and right";
const text2 = "Hit Spacebar to shoot a bullet directly upwards";
const text3 = "When you click the mouse, the player shoots a bullet in the direction of the mouse";
const text4 = "Bullets generated by mouseclicks decay over time and work only in a short range";
const text5 = "Homing bots follow the player and target the player"
const text6 = "The Base Health reduced when the base is hit by incoming ";
const text7 = "The game ends when Base Health is zero or if the player is hit by a bot";

let circles = [];
let mouse = {x : 0, y : 0};

function resizeCanvas(){
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
}
resizeCanvas();

function Circle(){
    this.x = Math.round(Math.random()*canvas.width);
    this.y = Math.round(Math.random()*canvas.height);
    this.r = 1.2;
    this.velocityX = (Math.random() - 0.5)*0.7;
    this.velocityY = (Math.random() - 0.5)*0.7;
    this.closeToMouse = false;

    this.draw = function(){
        c.beginPath();
        c.fillStyle = "white";
        c.arc(this.x, this.y, this.r, 0, Math.PI*2);
        c.fill();
    }

    this.update = function(){
        if (this.x + this.r > canvas.width || this.x < 0){
            this.velocityX = -this.velocityX;
        }
        if (this.y + this.r > canvas.height || this.y < 0){
            this.velocityY = -this.velocityY;
        }
        this.x += this.velocityX;
        this.y += this.velocityY;
        this.draw();
    }
}

function instructions(){
    c.fillStyle = "white";
    c.font = "20px Courier New";
    c.fillText("Instructions", canvas.width*0.42 - 30, canvas.height*0.1);

    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text1, canvas.width*0.25, canvas.height*0.2);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text2, canvas.width*0.25, canvas.height*0.28);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text3, canvas.width*0.25, canvas.height*0.36);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text4, canvas.width*0.25, canvas.height*0.44);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text5, canvas.width*0.25, canvas.height*0.52);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text6, canvas.width*0.25, canvas.height*0.6);
    c.fillStyle = "white";
    c.font = "15px Courier New";
    c.fillText(text7, canvas.width*0.25, canvas.height*0.68);
    c.fillStyle = "white"
    c.fillRect(canvas.width*0.4, canvas.height*0.8, 150, 50);
    c.fillStyle = "black";
    c.font = "20px Courier New";
    c.fillText("Continue",canvas.width*0.42, canvas.height*0.85)

}

function checkClick(mouseX, mouseY, x, y, width, height){
    return mouseX > x && mouseX < x + width && mouseY > y && mouseY < y + height;
}

document.addEventListener("mousedown", function ifClick(e){
    if (checkClick(e.x, e.y, canvas.width*0.4, canvas.height*0.8, 150, 50)){
        document.querySelector("body").style.cursor = "pointer";
        console.log(document.querySelector("body").style);
        window.location = "index2.html";
    }
});

document.addEventListener("mousemove", (e) => {
    mouse.x = e.x;
    mouse.y = e.y;
    if (checkClick(e.x, e.y, canvas.width*0.4, canvas.height*0.8, 150, 50)){
        document.querySelector("body").style.cursor = "pointer";
    }
    else{
        document.querySelector("body").style.cursor = "auto";
    }
    
});

for (var i = 0; i < 120; i++){
    var circle = new Circle();
    circles.push(circle);
}

function animate(){
    requestAnimationFrame(animate);

    resizeCanvas();

    c.clearRect(0, 0, canvas.width, canvas.height);

    circles.forEach((circle) => {
        if (Math.abs(circle.x - mouse.x) < 70 && Math.abs(circle.y - mouse.y) < 70){
            var speed = 0.9;
            var dx = mouse.x - circle.x;
            var dy = mouse.y - circle.y;
            var distance = (dx**2+dy**2)**0.5;
            circle.velocityX = speed*dx/distance;
            circle.velocityY = speed*dy/distance;
            circle.closeToMouse = true;
        }
        else if (circle.closeToMouse){
            circle.closeToMouse = false;
            circle.velocityX = Math.random() - 0.5;
            circle.velocityY = Math.random() - 0.5;
        }
        
        circle.update();
    });

    instructions();

}
animate();
/*Use Arrow keys or W and D to move the player left and right
Hit Spacebar to shoot a bullet directly upwards
When you click the mouse, the player shoots a bullet in the direction of the mouse
The Base Health reduced when the base is hit by incoming bots
The game ends when Base Health is zero or if the player is hit by a bot*/ 